### ISSUE TITLE
หน้า กรรมการ สอบ ของ ก1

### ISSUE THREAD

**Issue by ibotdotout** [sdayu/PSU-thesis-latex-template#4]
<img width="722" alt="screen shot 2558-08-25 at 16 15 22" src="https://cloud.githubusercontent.com/assets/686676/9463325/39a20132-4b46-11e5-847b-ed6e80753180.png">

**Comment by sdayu** [comment]
I fixed it with \raggedleft command, but I don't have OSX for test it. Please confirm if it's ok.
https://github.com/sdayu/PSU-thesis-latex-template/commit/35f81ba0fe4318f04592946f1e664606456d8dda

**Comment by ibotdotout** [comment]
<img width="692" alt="screen shot 2558-08-31 at 11 54 33" src="https://cloud.githubusercontent.com/assets/686676/9572265/21f79e76-4fd7-11e5-9d81-ce4678e887a5.png">

Result on OS X. That's ok.
