### ISSUE TITLE
หน้า vitae 

### ISSUE THREAD

**Issue by ibotdotout** [sdayu/PSU-thesis-latex-template#5]
<img width="702" alt="screen shot 2558-08-25 at 16 12 49" src="https://cloud.githubusercontent.com/assets/686676/9463355/5fcefc2a-4b46-11e5-880e-330df7d5d033.png">

มหาวิทยาลัย และ ปีการศึกษา ควรอยู่บรรทัดเดียวกันกับ คณะ

**Comment by sdayu** [comment]
Please check following this commit
https://github.com/sdayu/PSU-thesis-latex-template/commit/adee0317d5d75d84f67433ae7c4cc2411b04b976

**Comment by ibotdotout** [comment]
<img width="702" alt="screen shot 2558-08-31 at 11 52 59" src="https://cloud.githubusercontent.com/assets/686676/9572251/e5a44faa-4fd6-11e5-8082-496fc2b8603a.png">

Result on Xelatex OS X
