### ISSUE TITLE
ช่องไฟ และ ระยะระหว่างบรรทัด ?

### ISSUE THREAD

**Issue by ibotdotout** [sdayu/PSU-thesis-latex-template#8]
![screen shot 2558-09-08 at 12 28 08](https://cloud.githubusercontent.com/assets/686676/9727088/3a20bd62-5625-11e5-9122-5c1990f619f8.png)

เท่าที่สังเกต ช่องไฟ และ ระยะระหว่างบรรทัดของ template นี้ค่อนข้างเบียดกันมาก
เมื่อเทียบเคียงกันกับวิทยานิพนธ์ทั่วไป

แบบไหน จะเหมาะสมกว่ากันครับ ?

**Comment by sdayu** [comment]
อันด้านขวาคือเขาเราใช้เปล่า จะให้เพิ่มดีไหม

**Comment by sdayu** [comment]
Please check this commit https://github.com/sdayu/PSU-thesis-latex-template/commit/b97aa39063de99dc01f780b20654f3ba2021f304 . I have modified it with baselinkeskip

**Comment by sdayu** [comment]
Please check this commit https://github.com/sdayu/PSU-thesis-latex-template/commit/72d6c4c1e635c5a460cd13dfab7f5dba2d103d35, which improved the spacing
